version: '3'

services:

  wordpress:
    image: wordpress:6.2
    container_name: granito_web
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: granitodb
    volumes:
      - ./wordpress/:/var/www/html

  db:
    image: mysql:8.0
    container_name: granito_db
    environment:
      MYSQL_DATABASE: granitodb
      MYSQL_USER: granito
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql

volumes:
  wordpress:
  db: